### ISSUE TITLE
Getting this error message 

### ISSUE THREAD

**Issue by NuclearWaffle0** [Mustard2/MustardSimplify#7] opened 2023-09-13 20:26 UTC
Python: Traceback (most recent call last):
  File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Simplify.py", line 579, in execute
    add_prop_status(obj.MustardSimplify_Status.modifiers, [mod.name, mod.show_viewport])

  File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Simplify.py", line 534, in add_prop_status
    add_item = collection.add()
TypeError: bpy_prop_collection.add(): not supported for this collection

It seems to only happen in this specific scene for me, but I am not sure what specifically in this scene is causing it. I asked ChatGPT about it and it said, it may be due to an incorrect usage of the add function. Or a collection mismatch. Can't really give an in-depth report since I have like very little experience with Python, let alone blender's API ^.^;

**Comment by Mustard2** [comment] 2023-09-14 10:14
Hi! Thanks for reporting this bug.

Do you have the scene where this happens, so i can check it (even without textures, you can upload on wetransfer)?

**Comment by NuclearWaffle0** [comment] 2023-09-14 13:30
Yup! It's this scene https://open3dlab.com/project/34235/

If you're not comfy clicking links it's "Japanese Streets" on Open3DLab

**Comment by NuclearWaffle0** [comment] 2023-09-14 14:22
Uhh, sorry didn't see the last part of your reply Here's the link! https://we.tl/t-BuXtKw00Cw

**Comment by Mustard2** [comment] 2023-09-14 16:39
The problem is related to the fact that there are linked Objects, and when the add-on tries to change some properties, it fails.

For the moment I think I'll put a check, if it's linked it will not be simplified to avoid these errors.

**Comment by Mustard2** [comment] 2023-09-14 16:56
I close this issue as it's fixed in the latest version in the last commit (attacched also here):

[mustard_simplify.py.zip](https://github.com/Mustard2/MustardSimplify/files/12611441/mustard_simplify.py.zip)

I tested it on your scene, and the add-on should now be able to complete its work. But if you still have any issue, feel free to re-open this issue, or open a new one. :)

**Closed by Mustard2** 2023-09-14 16:56 UTC
Labels: bug

**Comment by NuclearWaffle0** [comment] 2023-09-14 18:31
Awesome, thanks Mustard! And I'll be sure to do that if I come across something else ^o^
